export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const WRONG_LOGIN_CREDENTIALS = "WRONG_LOGIN_CREDENTIALS";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const UPDATE_USER_DATA = "UPDATE_USER_DATA";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";
export const PASSWORD_UPDATED = "PASSWORD_UPDATED";
export const PASSWORD_UPDATED_FAILED = "PASSWORD_UPDATED_FAILED";
export const LEAVE_GROUP = "LEAVE_GROUP";
export const JOIN_GROUP = "JOIN_GROUP";
export const WRONG_GROUP_CREDENTIALS = "WRONG_GROUP_CREDENTIALS";
export const FAILED_TO_REGISTER_GROUP = "FAILED_TO_REGISTER_GROUP";
export const SUCCESSFULLY_REGISTERED_GROUP = "SUCCESSFULLY_REGISTERED_GROUP";
export const CLEAR_MODAL_MESSAGES = "CLEAR_MODAL_MESSAGES";
export const CLEAR_USER_UPDATE_MODAL = "CLEAR_USER_UPDATE_MODAL";
export const CLEAR_REGISTER_GROUP_MODAL = "CLEAR_REGISTER_GROUP_MODAL";



export const FETCH_USER_BUGS = "FETCH_USER_BUGS";
export const FETCH_ORGANIZATION_BUGS = "FETCH_ORGANIZATION_BUGS";
export const FETCH_CURRENT_BUG = "FETCH_CURRENT_BUG";
export const REMOVE_CURRENT_BUG = "REMOVE_CURRENT_BUG";
export const UPDATE_BUG = "UPDATE_BUG";
export const REPORT_BUG_SUCCESS = "REPORT_BUG_SUCCESS";
export const REPORT_BUG_FAILURE = "REPORT_BUG_FAILURE";
export const CLEAR_REPORT_SUCCESS_MESSAGE = "CLEAR_REPORT_SUCCESS_MESSAGE";
export const SEARCH_ALL_BUGS = "SEARCH_ALL_BUGS";
export const CLEAR_SEARCH_BUGS = "CLEAR_SEARCH_BUGS";
export const NO_MATCHING_RESULTS = "NO_MATCHING_RESULTS";
export const SORT_USER_BUGS = "SORT_USER_BUGS";
export const SORT_GROUP_BUGS = "SORT_GROUP_BUGS";


export const FETCH_BUG_COMMENTS = "FETCH_BUG_COMMENTS";
export const POST_NEW_COMMENT = "POST_NEW_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";