export const LOGIN_USER = "LOGIN_USER";
export const WRONG_LOGIN_CREDENTIALS = "WRONG_LOGIN_CREDENTIALS";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const FETCH_USER_BUGS = "FETCH_USER_BUGS";
export const FETCH_ORGANIZATION_BUGS = "FETCH_ORGANIZATION_BUGS";
export const FETCH_CURRENT_BUG = "FETCH_CURRENT_BUG";
export const REMOVE_CURRENT_BUG = "REMOVE_CURRENT_BUG";